# -*- coding: utf-8 -*-
"""ATCliveConverterX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfinhmQCPfMhhvMKoxqngjZKsterHVTP
"""

!pip install pydub

import time
import requests
import os
from pydub import AudioSegment
from io import BytesIO

# ATC audio file
# audio_url = "https://archive.liveatc.net/kgso/KGSO1-App-Dep-Jun-01-2024-0000Z.mp3"


# Times
t = ['0000Z','0030Z','0100Z','0130Z','0200Z','0230Z','0300Z','0330Z',
     '0400Z','0430Z','0500Z','0530Z','0600Z','0630Z','0700Z','0730Z','0800Z',
     '0830Z','0900Z','0930Z','1000Z','1030Z','1100Z','1130Z','1200Z','1230Z',
     '1300Z','1330Z','1400Z','1430Z','1500Z','1530Z','1600Z','1630Z','1700Z',
     '1730Z','1800Z','1830Z','1900Z','1930Z','2000Z','2030Z','2100Z','2130Z',
     '2200Z','2230Z','2300Z','2330Z']

# Function to download audio file and convert to WAV format
def download_and_convert_audio(url, folder_path):
    # Create folder if it doesn't exist
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    # Sending GET request to the URL
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3',
        'Referer': 'https://archive.liveatc.net/'
    }
    response = requests.get(url, headers=headers)

    # Request success check
    if response.status_code == 200:
        # Convert mp3 to wav
        audio_data = AudioSegment.from_mp3(BytesIO(response.content))
        wav_file_name = os.path.join(folder_path, os.path.basename(url).replace('.mp3', '.wav'))
        audio_data.export(wav_file_name, format="wav")
        print(f"Audio downloaded and converted successfully: {wav_file_name}")
    else:
        print(f"Failed to download audio: {response.status_code}")



# Folder path (Relative path)
# folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_ATIS"
# folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_Approach_Departure"
# folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_Approach_Departure_South"
# folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_Approach_Departure_West"
# folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_DEL_GND"
folder_path = "/content/drive/MyDrive/ATC_wav/KGSO_TOWER"


def download_ATC():
# <source src="https://archive.liveatc.net/kgso/KGSO1-App-Dep-West-May-29-2024-0000Z.mp3" type="audio/mpeg">


  for i in t:

    # Linkes for each frequency tower
    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-Jun-01-2024-0000Z.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-South-Jun-01-2024-0000Z.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-West-Jun-01-2024-0000Z.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-ATIS-Jun-01-2024-0000Z.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-Del-Gnd-Jun-01-2024-0000Z.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-Twr-Jun-01-2024-0000Z.mp3"

    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-Jun-01-2024-{i}.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-South-Jun-01-2024-{i}.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-App-Dep-West-Jun-01-2024-{i}.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-ATIS-Jun-01-2024-{i}.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-Del-Gnd-Jun-01-2024-{i}.mp3"
    # "https://archive.liveatc.net/kgso/KGSO1-Twr-Jun-01-2024-{i}.mp3"




    # audio_url=f"https://archive.liveatc.net/kgso/KGSO1-App-Dep-Jun-01-2024-{i}.mp3"
    audio_url=f"https://archive.liveatc.net/kgso/KGSO1-Twr-Jun-01-2024-{i}.mp3"

    download_and_convert_audio(audio_url, folder_path)


# # Function call
# download_and_convert_audio(audio_url, folder_path)

download_ATC()

from google.colab import drive
drive.mount('/content/drive')

